spring.application.name=backend-pulseira

# Usa o Atlas quando MONGODB_URI estiver definida; usa MongoDB local como alternativa.
spring.mongodb.uri=mongodb://nicolly_db_user:nimeire25@ac-bxktbf6-shard-00-00.jg8gxnf.mongodb.net:27017,ac-bxktbf6-shard-00-01.jg8gxnf.mongodb.net:27017,ac-bxktbf6-shard-00-02.jg8gxnf.mongodb.net:27017/?ssl=true&replicaSet=atlas-ms39aa-shard-0&authSource=admin&appName=cluster-pulseira
spring.mongodb.database=pulseira_db
